#lang racket

(define cd (lambda(system)
             (lambda(d)
               (if (equal? "/" d)
                   (make-system(flatten(cons(cdr(cons(get-name system)
                                                     (remove(list-ref(list-ref system 0)2)(get-name system))))
                                            (string-append(string-join
                                                           (take(string-split(list-ref(list-ref system 0)2)"/")1)"/")"/")))
                               (get-drive system)(get-user system)(get-carpetas system))
                   (if (member d (flatten(list-ref system 3)))
                       (make-system(flatten(cons(cdr(cons(get-name system)(remove(list-ref(list-ref system 0)2)
                                                                                 (get-name system)))) d))
                                   (get-drive system)(get-user system)(get-carpetas system))
                       (if(member (string-append(list-ref(list-ref system 0)2)d"/") (flatten(list-ref system 3)))
                          (make-system(flatten(cons(cdr(cons(get-name system)(remove(list-ref(list-ref system 0)2)
                                                                                    (get-name system))))
                                                   (string-append(list-ref(list-ref system 0)2)d"/")))
                                      (get-drive system)(get-user system)(get-carpetas system))
                          (if(equal? ".." d)
                             (make-system(flatten(cons(cdr(cons(get-name system)(remove(list-ref(list-ref system 0)2)
                                                                                       (get-name system))))
                                                      (string-append(string-join(take(string-split(list-ref(list-ref system 0)2)"/")
                                                                          (- (length(string-split(list-ref(list-ref system 0)2)"/"))1))"/")"/")))
                                         (get-drive system)(get-user system)(get-carpetas system))
                             (make-system(get-name system)(get-drive system)(get-user system)(get-carpetas system)))))))))